_type: export
__export_format: 4
__export_date: __FULL_DATE__
__export_source: insomnia.desktop.app:v2022.7.1
resources:
  - _id: __WORKSPACE_UUID__
    parentId: null
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    name: __PROJECT_NAME__
    description: ""
    scope: collection
    _type: workspace
  - _id: __ENVIRONMENT_UUID__
    parentId: __WORKSPACE_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    name: Base Environment
    data: {}
    dataPropertyOrder: {}
    color: null
    isPrivate: false
    metaSortKey: -1500000
    _type: environment
  - _id: __AMAZON_ENV_UUID__
    parentId: __ENVIRONMENT_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    name: Amazon
    data:
      amazonURL: https://my-amazon-url.execute-api.us-east-1.amazonaws.com
      stage: dev
      apiKey: "my-amazon-api-key"
    dataPropertyOrder:
      "&":
        - amazonURL
        - stage
        - apiKey
    color: "#df308d"
    isPrivate: false
    metaSortKey: -1100000
    _type: environment
  - _id: __LOCAL_ENV_UUID__
    parentId: __ENVIRONMENT_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    name: local
    data:
      amazonURL: http://localhost:3003
      stage: dev
      apiKey: my-local-api-key
    dataPropertyOrder:
      "&":
        - amazonURL
        - stage
        - apiKey
    color: "#1358c9"
    isPrivate: false
    metaSortKey: -1900000
    _type: environment
  - _id: __API_SPEC_UUID__
    parentId: __WORKSPACE_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    fileName: __PROJECT_NAME__
    contents: ""
    contentType: yaml
    _type: api_spec
  - _id: __REQUEST_GROUP_UUID__
    parentId: __WORKSPACE_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    name: __SINGLE_TITLE__
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -90000000
    _type: request_group
  - _id: __REQUEST_POST_UUID__
    parentId: __REQUEST_GROUP_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    url: "{{ _.amazonURL }}/{{ _.stage }}/__PLURAL__"
    name: __SINGLE_TITLE__
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: >-
        {
        	"description": "In Colombia we love soccer so",
        	"category": "a1c5abb7-50e4-4ae4-96a8-c36e96ba3df2",
        	"name": "Independiente Medellin Soccer Game",
        	"hoursOfService": 6,
        	"date": "Fri Nov 11 2022"
        }
    parameters: []
    headers:
      - id: __KEY_PAIR_UUID__
        name: x-api-key
        value: "{{ _.apiKey }}"
        description: ""
      - name: Content-Type
        value: application/json
    authentication: {}
    metaSortKey: -8000000
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: __REQUEST_PUT_UUID__
    parentId: __REQUEST_GROUP_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    url: "{{ _.amazonURL }}/{{ _.stage
      }}/__PLURAL__/my-id"
    name: __SINGLE_TITLE__
    description: ""
    method: PUT
    body:
      mimeType: application/json
      text: |-
        {
        	"category": "ya bajale",
        	"gallery": false
        }
    parameters: []
    headers:
      - id: __KEY_PAIR_UUID__
        name: x-api-key
        value: "{{ _.apiKey }}"
        description: ""
      - name: Content-Type
        value: application/json
    authentication: {}
    metaSortKey: -17700000
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: __REQUEST_GETALL_UUID__
    parentId: __REQUEST_GROUP_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    url: "{{ _.amazonURL }}/{{ _.stage }}/__PLURAL__"
    name: All __PLURAL_TITLE__
    description: ""
    method: GET
    body: {}
    parameters: []
    headers:
      - id: __KEY_PAIR_UUID__
        name: x-api-key
        value: "{{ _.apiKey }}"
        description: ""
    authentication: {}
    metaSortKey: -22500000
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: __REQUEST_GET_UUID__
    parentId: __REQUEST_GROUP_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    url: "{{ _.amazonURL }}/{{ _.stage
      }}/__PLURAL__/my-id"
    name: __SINGLE_TITLE__ ID
    description: ""
    method: GET
    body: {}
    parameters: []
    headers:
      - id: __KEY_PAIR_UUID__
        name: x-api-key
        value: "{{ _.apiKey }}"
        description: ""
    authentication: {}
    metaSortKey: -12900000
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: __REQUEST_DELETE_UUID__
    parentId: __REQUEST_GROUP_UUID__
    modified: __EPOCH_PLUS_ONE__
    created: __EPOCH_TIME__
    url: "{{ _.amazonURL }}/{{ _.stage }}/__PLURAL__/my-id"
    name: __SINGLE_TITLE__ ID
    description: ""
    method: DELETE
    body: {}
    parameters: []
    headers:
      - id: __KEY_PAIR_UUID__
        name: x-api-key
        value: "{{ _.apiKey }}"
        description: ""
    authentication: {}
    metaSortKey: -152100000
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
